### PR TITLE
update h3

### PR DESCRIPTION
**Pull request by vloveits**

### CODE REVIEW

**Comment by vloveits** [comment]
update file

**Comment by vloveits** [comment]
fix merge

**Review by vloveits — COMMENTED** [review]
oke

**Review by vloveits-sc — APPROVED** [review]

**Comment by vloveits-sc** [comment]
review ok

**Review by vloveits-sc — DISMISSED** [review]
change to meging

**Review by vloveits-sc — APPROVED** [review]
oke

**Review by vloveits-sc — APPROVED** [review]
oke

**Review by vloveits — COMMENTED** [review]
oke

**Pull request closed without merging**
